### ISSUE TITLE
The Generative Programs Framework

### ISSUE THREAD

**Issue by samkariu** [papers-we-love/nairobi#10]
URL: https://arxiv.org/pdf/2307.11282.pdf
Abstract

        Recently there has been significant interest in using causal modelling techniques to understand the structure of physical theories. However, the
        notion of ‘causation’ is limiting - insisting that a physical theory must involve
        causal structure already places significant constraints on the form that theory
        may take. Thus in this paper, we aim to set out a more general structural
        framework. We argue that any quantitative physical theory can be represented
        in the form of a generative program, i.e. a list of instructions showing how
        to generate the empirical data; the information-processing structure associated
        with this program can be represented by a directed acyclic graph (DAG). We
        suggest that these graphs can be interpreted as encoding relations of ‘ontological
        priority,’ and that ontological priority is a suitable generalisation of causation
        which applies even to theories that don’t have a natural causal structure. We
        discuss some applications of our framework to philosophical questions about
        realism, operationalism, free will, locality and fine-tuning.

**Comment by profnandaa** [comment]
Looking forward to this one. Let's do it as the first one in the new year. I'll schedule it  and send invites - Jan 9, 2024.

**Comment by samkariu** [comment]
Ok. Sounds good.

**Comment by profnandaa** [comment]
Scheduled - https://www.linkedin.com/events/pwlnairobimeetup-10-thegenerati7140569262884110336/comments/

**Comment by profnandaa** [comment]
Thanks @samkariu for presenting. Here's the recording - https://www.youtube.com/watch?v=NK2s-0wHJ0M
